import type { ID, ISODateString, SocialPlatform } from './common';

/**
 * A raw entry written by the user. Mirrors the `journal_entries` table.
 */
export interface JournalEntry {
  id: ID;
  userId: ID;
  /** Optional title; can be derived from content if absent. */
  title: string | null;
  content: string;
  /** Optional embedding (pgvector) for memory retrieval. */
  embedding: number[] | null;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/**
 * A single agent's rewrite of a source idea for a specific platform.
 * Generated by the "One Story, Multiple Narratives" feature.
 */
export interface Narrative {
  agentId: ID;
  agentName: string;
  platform: SocialPlatform;
  content: string;
}

/**
 * The full multi-narrative output for a single source idea.
 */
export interface RewriteResult {
  id: ID;
  userId: ID;
  /** The original idea the user typed. */
  sourceText: string;
  platform: SocialPlatform;
  narratives: Narrative[];
  createdAt: ISODateString;
}
